name: vts_kit_flutter_component_example
description: Flutter Component Demo App

version: 1.0.8+9

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  vts_component:
    path: '../vts_component-git/'

  flutter_webview_plugin: ^0.4.0
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  device_info_plus: ^4.1.2
  android_id: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/image.png
    - lib/assets/images/image1.png
    - lib/assets/images/red.png
    - lib/assets/images/purple.png
    - lib/assets/images/pink.png
    - lib/assets/images/orange.png
    - lib/assets/images/image2.png
    - lib/assets/images/img.png
    - lib/assets/images/img1.png
    - lib/assets/images/img2.png
    - lib/assets/images/card.png
    - lib/assets/images/card1.png
    - lib/assets/images/card2.png
    - lib/assets/images/card3.png
    - lib/assets/images/card5.png
    - lib/assets/images/card4.png
    - lib/assets/images/gflogo.png
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/avatar5.png
    - lib/assets/images/avatar6.png
    - lib/assets/images/avatar7.png
    - lib/assets/images/avatar8.png
    - lib/assets/images/avatar9.png
    - lib/assets/images/avatar10.png
    - lib/assets/images/avatar11.png
    - lib/assets/images/avatar12.png
    - lib/assets/images/s1.png
    - lib/assets/images/s2.png
    - lib/assets/images/s3.png
    - lib/assets/images/s4.png
    - lib/assets/images/s5.png
    - lib/assets/images/story.jpg
    - lib/assets/images/i1.png
    - lib/assets/images/i2.png
    - lib/assets/images/i3.png
    - lib/assets/images/i4.png
    - lib/assets/images/e5.png
    - lib/assets/images/e4.png
    - lib/assets/images/e3.png
    - lib/assets/images/e2.png
    - lib/assets/images/e1.png

    - lib/assets/images/default-avatar-1.png
    - lib/assets/images/default-avatar-2.png
    - lib/assets/images/exam-avatar-1.png
    - lib/assets/images/exam-avatar-2.png
    - lib/assets/images/exam-avatar-3.png
    - lib/assets/images/exam-avatar-4.png
    - lib/assets/images/exam-avatar-5.png
    - lib/assets/images/exam-avatar-6.png
    - lib/assets/images/image-1.png
    - lib/assets/images/image-2.png
    - lib/assets/images/image-3.png
    - lib/assets/images/image-4.png
    - lib/assets/images/image-5.png
    - lib/assets/images/image-6.png
    - lib/assets/images/image-7.png
    - lib/assets/images/image-8.png
    - lib/assets/images/image-9.png
    - lib/assets/images/image-10.png
    - lib/assets/images/image-11.png
    - lib/assets/images/image-12.png
    - lib/assets/images/image-13.png
    - lib/assets/images/image-14.png
    - lib/assets/images/image-15.png
    - lib/assets/images/image-16.png
    - lib/assets/images/image-17.png

    - lib/assets/images/card-image-1.png
    - lib/assets/images/card-image-2.png
    - lib/assets/images/card-image-3.png
    - lib/assets/images/card-image-4.png
    - lib/assets/images/card-image-5.png

    - lib/assets/images/carousel-image-1.png
    - lib/assets/images/carousel-image-2.png
    - lib/assets/images/carousel-image-3.png
    - lib/assets/images/carousel-image-4.png
    - lib/assets/images/carousel-image-5.png
    - lib/assets/images/carousel-image-6.png

    - lib/assets/gif/success1.gif
    - lib/assets/icons/allign.png
    - lib/assets/icons/Rotation.png
    - lib/assets/icons/scaling.png
    - lib/assets/icons/size.png
    - lib/assets/icons/slide.png
    - lib/assets/icons/gflogo.png

    - lib/assets/icons/standard_button.svg
    - lib/assets/icons/pill_button.svg
    - lib/assets/icons/icon_button.svg
    - lib/assets/icons/social_button.svg
    - lib/assets/icons/link_button.svg
    - lib/assets/icons/segment_tab.svg
    - lib/assets/icons/icon_tab.svg
    - lib/assets/icons/labeled_tab.svg
    - lib/assets/icons/bottom_icon_tab.svg
    - lib/assets/icons/bottom_labeled_tab.svg

  fonts:
    - family: GFFontIcons
      fonts:
        - asset: lib/assets/fonts/gfFontIcon.ttf
          weight: 400

    - family: GFFontIcons2
      fonts:
        - asset: lib/assets/fonts/gfFontIcons2.ttf
          weight: 400

    - family: GFSocialFonts
      fonts:
        - asset: lib/assets/fonts/gfSocialFonts.ttf
          weight: 400

    - family: GFIconFonts
      fonts:
        - asset: lib/assets/fonts/gfIconFonts.ttf
          weight: 400

    - family: GFIcons
      fonts:
        - asset: lib/assets/fonts/loader.ttf
          weight: 400

    - family: GFIconsnew
      fonts:
        - asset: lib/assets/fonts/newcomp.ttf
          weight: 400

    - family: GFIconsneww
      fonts:
        - asset: lib/assets/fonts/new.ttf
          weight: 400

    ### Sarabun
    - family: Sarabun
      fonts:
        - asset: lib/assets/fonts/Sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Sarabun/Sarabun-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Sarabun/Sarabun-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Sarabun/Sarabun-ExtraBold.ttf
          weight: 800

    ### Sarabun Italic
    - family: Sarabun
      fonts:
        - asset: lib/assets/fonts/Sarabun/Sarabun-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Sarabun/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    ### BeauSansPro
    - family: BeauSansPro
      fonts:
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProThin.ttf
          weight: 100
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProLight.ttf
          weight: 300
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansPro.ttf
          weight: 400
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBbook.ttf
          weight: 500
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProSemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBold.ttf
          weight: 700
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBlack.ttf
          weight: 900

    ### BeauSansPro Italic
    - family: BeauSansPro
      fonts:
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProLightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProItalic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBbookItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProSemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/BeauSansPro/FSPFBeauSansProBlackItalic.ttf
          weight: 900
          style: italic
